In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io

In [18]:
url = "https://en.wikipedia.org/wiki/Nationwide_opinion_polling_for_the_2016_United_States_presidential_election"
response = requests.get(url)
soup = BeautifulSoup(response.text)

response.status_code

200

In [19]:
tables = soup.find_all("table", class_="wikitable")

In [47]:
table_html = str(tables[0])  # You can change this index to get a different table
Aggregate_Polls_2016_raw = pd.read_html(io.StringIO(table_html))[0]

In [48]:
print("Raw Table Preview:")
display(Aggregate_Polls_2016_raw.head())

Raw Table Preview:

,Race,Poll model,Hillary Clinton Democratic,Donald Trump Republican,Gary Johnson Libertarian,Jill Stein Green,Leading by (points)
0,Two-way,270toWin[4],47.2%,43.6%,—,—,3.6
1,Two-way,BBC[5],48.0%,44.0%,—,—,4.0
2,Two-way,HuffPost Pollster[6],47.3%,42.0%,—,—,5.3
3,Two-way,New York Times[7],45.9%,42.8%,—,—,3.1
4,Two-way,Real Clear Politics[8],46.8%,43.6%,—,—,3.2

In [49]:
df_table_1.to_csv("Aggregate_Polls_2016_raw.csv", index=False)

In [44]:
table_html = str(tables[1])  # You can change this index to get a different table
Two_way_race_After_convention_nominations = pd.read_html(io.StringIO(table_html))[0]

In [45]:
print("Raw Table Preview:")
display(Two_way_race_After_convention_nominations.head())

Raw Table Preview:

,Poll source,Date,Hillary Clinton Democratic,Donald Trump Republican,Leading by (points),Sample size,Margin of error
0,UPI/CVoter[13],"November 1–7, 2016",49%,46%,3,1728,± 3.0%
1,YouGov/The Economist[14],"November 4–7, 2016",49%,45%,4,3677,± 1.7%
2,Bloomberg News/Selzer[15],"November 4–6, 2016",46%,43%,3,799,± 3.5%
3,ABC News/Washington Post[16],"November 3–6, 2016",49%,46%,3,2220,± 2.5%
4,Fox News[17],"November 3–6, 2016",48%,44%,4,1295,± 2.5%

In [50]:
df_table_2.to_csv("Two_way_race_After_convention_nominations_raw.csv", index=False)

In [51]:
# Select one table and turn it into a DataFrame
table_html = str(tables[2])  
Polls_conducted_in_2016 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Polls_conducted_in_2016.to_csv("Polls_conducted_in_2016_raw.csv", index=False)

Polls_conducted_in_2016.head()

,Poll source,Date,Democratic candidate,%,Republican candidate,%.1,Leading by %,Sample size,Margin of error
0,Ipsos/Reuters[277],"July 25–29, 2016",Hillary Clinton,40%,Donald Trump,35%,5,1290,± 2.4%
1,Rasmussen Reports[278],"July 26–27, 2016",Hillary Clinton,43%,Donald Trump,42%,1,1000,± 3.0%
2,Ipsos/Reuters[279],"July 22–26, 2016",Hillary Clinton,37%,Donald Trump,39%,2,963,± 4.0%
3,USC/Los Angeles Times[280],"July 20–26, 2016",Hillary Clinton,40%,Donald Trump,47%,7,2150,± 3%
4,Economist/YouGov[281],"July 23–24, 2016",Hillary Clinton,47%,Donald Trump,42%,5,1300,± 4.5%

In [52]:
# Select one table and turn it into a DataFrame
table_html = str(tables[6])  
Three_Way_Race_2016 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Three_Way_Race_2016.to_csv("Three_Way_Race_2016_raw.csv", index=False)

Three_Way_Race_2016.head()

,Poll source,Date,Hillary Clinton Democratic,Donald Trump Republican,Gary Johnson Libertarian,Leading by (points),Sample size,Margin of error
0,Google Consumer Surveys[536],"November 1–7, 2016",38%,36%,5%,2,26574,± 0.65%
1,Angus Reid Institute[537],"November 1–4, 2016",48%,44%,6%,4,1151,± 2.9%
2,RAND American Life Panel[538],"October 20 – November 1, 2016",44%,35%,8%,9,2269,± 1.9%
3,Google Consumer Surveys[539],"October 20–24, 2016",39%,34%,6%,5,21240,±0.73%
4,Public Policy Polling[540],"October 20–21, 2016",46%,40%,5%,6,990,±3.18%

In [53]:
# Select one table and turn it into a DataFrame
table_html = str(tables[7])  
Polls_up_to_August_2 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Polls_up_to_August_2.to_csv("Polls_up_to_August_2_raw.csv", index=False)

Polls_up_to_August_2.head()

,Poll source,Date,Democratic candidate,%,Republican candidate,%.1,Libertarian candidate,%.2,Lead margin
0,"Fox News[267] Sample size: 1,022 Margin of err...","July 31 – August 2, 2016",Hillary Clinton,44%,Donald Trump,35%,Gary Johnson,12%,9
1,"Penn Schoen Berland[546] Sample size: 1,000 Ma...","July 29 – August 1, 2016",Hillary Clinton,45%,Donald Trump,40%,Gary Johnson,15%,5
2,"CBS News[273] Sample size: 1,131 Margin of err...","July 29–31, 2016",Hillary Clinton,43%,Donald Trump,38%,Gary Johnson,10%,5
3,"Morning Consult[275] Sample size: 1,931 Margin...","July 29–30, 2016",Hillary Clinton,41%,Donald Trump,36%,Gary Johnson,11%,5
4,"Morning Consult[282] Sample size: 2,502 Margin...","July 22–24, 2016",Hillary Clinton,36%,Donald Trump,40%,Gary Johnson,10%,4

In [55]:
# Select one table and turn it into a DataFrame
table_html = str(tables[9])  
Four_way_race_2016 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Four_way_race_2016.to_csv("Four_way_race_2016_raw.csv", index=False)

Four_way_race_2016.head()

,Poll source,Date,Hillary Clinton Democratic,Donald Trump Republican,Gary Johnson Libertarian,Jill Stein Green,Leading by (points),Sample size,Margin of error
0,YouGov/The Economist[14],"November 4–7, 2016",45%,41%,5%,2%,4,3677.0,± 1.7%
1,Insights West[563],"November 4–7, 2016",49%,45%,4%,1%,4,940.0,± 3.2%
2,Bloomberg News/Selzer[15],"November 4–6, 2016",44%,41%,4%,2%,3,799.0,± 3.5%
3,Gravis Marketing[564],"November 3–6, 2016",47%,43%,3%,2%,4,16639.0,± 0.8%
4,ABC News/Washington Post[16],"November 3–6, 2016",47%,43%,4%,1%,4,2220.0,± 2.5%

In [57]:
# Select one table and turn it into a DataFrame
table_html = str(tables[8])  
Polls_Up_to_Aug_2_Part_2_2016 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Polls_Up_to_Aug_2_Part_2_2016.to_csv("Polls_Up_to_Aug_2_Part_2_2016_raw.csv", index=False)

Polls_Up_to_Aug_2_Part_2_2016.head()

,Poll source,Date,Democratic candidate,%,Republican candidate,%.1,Third candidate,%.2,Lead margin
0,ABC News/Washington Post[363] Sample size: 823...,"May 16–19, 2016",Hillary Clinton,37%,Donald Trump,35%,Mitt Romney,22%,2
1,"Public Policy Polling[387] Sample size: 1,083 ...","March 24–26, 2016",Hillary Clinton,42%,Donald Trump,37%,Deez Nuts,10%,5
2,"Public Policy Polling[387] Sample size: 1,083 ...","March 24–26, 2016",Bernie Sanders,43%,Donald Trump,37%,Deez Nuts,8%,6
3,"Public Policy Polling[387] Sample size: 1,083 ...","March 24–26, 2016",Hillary Clinton,44%,Donald Trump,35%,Rick Perry,12%,9
4,"Public Policy Polling[387] Sample size: 1,083 ...","March 24–26, 2016",Bernie Sanders,43%,Donald Trump,34%,Rick Perry,12%,9

In [56]:
# Select one table and turn it into a DataFrame
table_html = str(tables[10])  
Five_way_race_2016 = pd.read_html(io.StringIO(table_html))[0]

# Export to CSV
Five_way_race_2016.to_csv("Five_way_race_2016_raw.csv", index=False)

Five_way_race_2016.head()

,Poll source,Date,Hillary Clinton Democratic,Donald Trump Republican,Gary Johnson Libertarian,Jill Stein Green,Evan McMullin Independent,Leading by (points),Sample size,Margin of error
0,Saint Leo University[578],"October 22–26, 2016",42%,31%,6%,1%,5%,11,1050,–
1,Public Policy Polling[149],"September 27–28, 2016",44%,40%,6%,1%,2%,4,933,±3.2%
2,Echelon Insights[151],"September 26–27, 2016",44%,39%,6%,2%,1%,5,1833,–
3,Public Policy Polling[214],"August 26–28, 2016",42%,37%,6%,4%,1%,5,881,±3.3%